PT-87 move preview feature to backend
VirtoCommerce/vc-module-customer-segments pull request #12
Opened 2021-04-16 07:44 UTC by ksavosteev

https://virtocommerce.atlassian.net/browse/PT-87

2021-04-16 10:33 UTC, Vectorfield4 requested changes

2021-04-16 10:33 UTC, Vectorfield4 commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/CustomerSegmentConditionPropertyValues.cs
> +            return result;
Rewrite to LINQ, please.
``` csharp
=> Properties.Where(prop => !prop.Values.IsNullOrEmpty())
                       .Select(...)
                       .ToList() // Do we really need list here?
```

2021-04-16 10:33 UTC, Vectorfield4 commented on src/VirtoCommerce.CustomerSegmentsModule.Data/Services/UserGroupEvaluator.cs
> +        public async Task<ICollection<UserGroupInfo>> EvaluateUserGroupsAsync(IEvaluationContext context)
We need tests for this method.

2021-04-16 10:33 UTC, Vectorfield4 commented on src/VirtoCommerce.CustomerSegmentsModule.Data/Services/UserGroupEvaluator.cs
> +        public async Task<ICollection<UserGroupInfo>> EvaluateUserGroupsAsync(IEvaluationContext context)
By the way, why are we returning ICollection instead of IEnumerable?

2021-04-16 10:33 UTC, Vectorfield4 commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/UserGroupInfo.cs
> +    public class UserGroupInfo
Add XML description for this class, please.

2021-04-16 10:33 UTC, Vectorfield4 commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/MemberSearchCriteraiBuilder.cs
> +        public MembersSearchCriteria Criteria { get; set; }
Any reason to make the setter not private?

2021-04-16 10:33 UTC, Vectorfield4 commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/MemberSearchCriteraiBuilder.cs
> +    public class MemberSearchCriteraiBuilder : IMemberSearchCriteriaBuilder
We need a test for every "WithSomething" method.

2021-04-16 10:33 UTC, Vectorfield4 commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/CustomerSegmentTree.cs
> +                BuildSearchCriteria(Children, builder);
Why do we pass base property to the protection method which already has access to the base property? Looks like a redundant parameter.

2021-04-16 10:33 UTC, Vectorfield4 commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/CustomerSegmentTree.cs
> +        protected virtual void BuildSearchCriteria(IList<IConditionTree> children, IMemberSearchCriteriaBuilder builder)
Rename this method to give more clearance what this method does. Maybe "EvaluateSearchCriteria"?

2021-04-16 10:33 UTC, Vectorfield4 commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/CustomerSegmentConditionPropertyValues.cs
> +            string result;
Remove this variable.

2021-04-16 10:33 UTC, Vectorfield4 commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/CustomerSegmentConditionPropertyValues.cs
> +        public class CustomerModelPropertyAttribute : Attribute
Move this class out and add a description.

2021-04-16 10:33 UTC, Vectorfield4 commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/CustomerSegmentConditionPropertyValues.cs
> +            var result = propertyName;
It's not a result. Remove this variable.

2021-04-16 10:33 UTC, Vectorfield4 commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/CustomerSegmentConditionPropertyValues.cs
> +        private IList<string> GetModelPropertiesParts()
Same, can we rewrite it to pure LINQ? If not can we reduce cognitive complexity?

2021-04-16 11:35 UTC, eMazeika reviewed
There had to be much js code removed (regarding filter previewing), but I can't see anything removed.

2021-04-16 11:38 UTC, ksavosteev commented
@eMazeika 

only customer-searchCriteria-builder.js will be removed

2021-04-20 07:48 UTC, Vectorfield4 approved these changes

2021-04-20 08:00 UTC, eMazeika commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/IMemberSearchCriteraiBuilder.cs
> +using VirtoCommerce.CustomerModule.Core.Model.Search;
fix typo in filename

2021-04-20 08:00 UTC, eMazeika commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/MemberSearchCriteraiBuilder.cs
> +using VirtoCommerce.CustomerModule.Core.Model;
fix typo in filename

2021-04-20 09:40 UTC, tatarincev requested changes

2021-04-20 09:40 UTC, tatarincev commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/IMemberSearchCriteriaBuilder.cs
> +        MembersSearchCriteria Build();
Better to do not include all fluent syntax into a interface, make them as extension methods instead

2021-04-20 09:40 UTC, tatarincev commented on src/VirtoCommerce.CustomerSegmentsModule.Core/Models/CustomerModelPropertyAttribute.cs
> +    public class CustomerModelPropertyAttribute : Attribute
How about rename to Searchable to be more close to sematic meaning?

2021-04-21 08:31 UTC, merged